server:
  port: 9092
spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
        uri: mongodb://localhost:27017/Microservices
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9094/eureka